// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathfinderManagement.Data;

namespace PathfinderManagement.Migrations
{
    [DbContext(typeof(PfDbContext))]
    partial class PfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("PathfinderManagement.Models.Counsellors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Counsellors");
                });

            modelBuilder.Entity("PathfinderManagement.Models.Pathfinders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CounsellorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CounsellorId");

                    b.ToTable("Pathfinders");
                });

            modelBuilder.Entity("PathfinderManagement.Models.Pathfinders", b =>
                {
                    b.HasOne("PathfinderManagement.Models.Counsellors", "Counsellor")
                        .WithMany()
                        .HasForeignKey("CounsellorId");
                });
#pragma warning restore 612, 618
        }
    }
}
